"""add open to post

Revision ID: 3cf52f78fc6d
Revises: 7b8c12977bde
Create Date: 2021-09-12 22:40:11.633632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf52f78fc6d'
down_revision = '7b8c12977bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'open')
    # ### end Alembic commands ###
