"""empty message

Revision ID: 266e028de96a
Revises: 0928a315fa3e
Create Date: 2021-09-10 20:31:27.873993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266e028de96a'
down_revision = '0928a315fa3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
