"""empty message

Revision ID: 20dd5a6fe2e7
Revises: 7c4d13886f8e
Create Date: 2021-09-14 17:05:17.905522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20dd5a6fe2e7'
down_revision = '7c4d13886f8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('posts', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'open',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'open',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('posts', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
