"""empty message

Revision ID: c2a330b9b10e
Revises: bc070121cd1d
Create Date: 2021-09-16 14:04:57.763849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a330b9b10e'
down_revision = 'bc070121cd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users_friends', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_friends', 'id')
    op.drop_column('friend_requests', 'id')
    # ### end Alembic commands ###
